var f=(t,e,s)=>{if(!e.has(t))throw TypeError("Cannot "+s)};var h=(t,e,s)=>(f(t,e,"read from private field"),s?s.call(t):e.get(t)),l=(t,e,s)=>{if(e.has(t))throw TypeError("Cannot add the same private member more than once");e instanceof WeakSet?e.add(t):e.set(t,s)},p=(t,e,s,a)=>(f(t,e,"write to private field"),a?a.call(t,s):e.set(t,s),s);var y=(t,e,s)=>(f(t,e,"access private method"),s);import{i as j,S}from"./assets/vendor-5b791d57.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const g of n.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&a(g)}).observe(document,{childList:!0,subtree:!0});function s(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(r){if(r.ep)return;r.ep=!0;const n=s(r);fetch(r.href,n)}})();const q="/goit-js-hw-11/assets/rejectedIcon-9956cb73.svg",O="/goit-js-hw-11/assets/izitoast-close-4cebbc46.svg";var c;class ${constructor(e=""){l(this,c,void 0);this.parent=e,p(this,c,"")}add(){p(this,c,document.querySelector(this.parent).innerHTML),document.querySelector(this.parent).innerHTML='<div id="spinner-container" style="display:flex; flex-direction:column; gap:15px; align-items:center;"><span class="js-processing-request">Loading images, please wait...</span><span class="loader"></span></div>'}remove(){document.querySelector(this.parent).innerHTML=h(this,c)}}c=new WeakMap;var u,d,L,m,F;class w{constructor(e=[],s=[""],a=""){l(this,d);l(this,m);l(this,u,void 0);this.parent=a,this.rawData=e,this.cleanData=y(this,d,L).call(this,s),p(this,u,y(this,m,F).call(this))}static testInput(e){return e.trim()?/^[a-z\s]+$/gi.test(e.trim()):!1}renderGallery(){document.querySelector(this.parent).innerHTML=h(this,u),console.log(this)}}u=new WeakMap,d=new WeakSet,L=function(e){return this.rawData.map(s=>{const a={};return e.forEach(r=>{a[r]=s[r]}),a})},m=new WeakSet,F=function(){return this.cleanData.map(s=>`<li class="js-gallery-item">
        <a class="js-image-container" href="${s.largeImageURL}"><img class="js-item-image" src="${s.webformatURL}" alt="${s.tags}" /></a>
        <ul class="js-item-desc">
          <li class="js-desc-wrapper"><span class="js-desc-prop">Likes</span><span class="js-desc-value">${s.likes}</span></li>
          <li class="js-desc-wrapper"><span class="js-desc-prop">Views</span><span class="js-desc-value">${s.views}</span></li>
          <li class="js-desc-wrapper"><span class="js-desc-prop">Comments</span><span class="js-desc-value">${s.comments}</span></li>
          <li class="js-desc-wrapper"><span class="js-desc-prop">Downloads</span><span class="js-desc-value">${s.downloads}</span></li>
        </ul>
      </li>`).join(`

`)};const o={form:document.querySelector(".js-search-form"),input:document.querySelector(".js-search-input"),container:document.querySelector(".js-gallery")},M="https://pixabay.com/api/",b={key:"42242477-df8643eaa45736c853493b589",image_type:"photo",orientation:"horizontal",safesearch:!0,q:null},v=new $(".js-gallery"),i={class:"js-izitoast-message",titleColor:"#FFFFFF",messageColor:"#FFFFFF",messageSize:"16px",position:"topRight",iconUrl:q,close:!1,buttons:[[`<button type="button" style="background-color: transparent;"><img src=${O}></button>`,function(t,e){t.hide({transitionOut:"fadeOut"},e)}]],onOpening:function(t,e){o.container.innerHTML="",o.input.blur(),o.input.addEventListener("focus",()=>{j.hide({transitionOut:"fadeOut"},e)},{once:!0})}};o.input.addEventListener("input",t=>{/^[a-z\s]+$/gi.test(t.target.value)||setTimeout(()=>{t.target.value=t.target.value.slice(0,-1)},100)});o.form.addEventListener("submit",t=>{if(t.preventDefault(),b.q=o.input.value.trim(),!w.testInput(o.input.value.trim())){i.message='Try something like "kitty", "best friends", "on the Moon" ;)',i.backgroundColor="#e0c34c",i.progressBarColor="#f7e28b",j.show(i),o.form.reset();return}fetch(`${M}?${new URLSearchParams(b)}`).then(e=>{if(!e.ok)throw new Error("Something went wrong!");return e.json()}).then(e=>{if(!e.hits.length){i.message="Sorry, there are no images matching your search query. Please try again!",i.backgroundColor="#EF4040",i.progressBarColor="#B51B1B",j.show(i),o.form.reset();return}v.add();const s=new w(e.hits,["largeImageURL","webformatURL","tags","likes","views","comments","downloads"],".js-gallery"),a=new S(".js-gallery a",{className:"lightbox-wrapper"});v.remove(),s.renderGallery(),a.refresh(),o.form.reset()}).catch(e=>console.log(e))});
//# sourceMappingURL=commonHelpers.js.map
